Added Docker Image worflow and update other workflow
tycrek/ass pull request #234
Opened 2023-10-09 13:51 UTC by Gauvino

## Checklist

- [X] I have read the [Contributing Guidelines]
- [X] I acknowledge that any submitted code will be licensed under the [ISC License]
- [X] I confirm that submitted code is my own work
- [X] I have tested the code, and confirm that it works

## Enviroment

- Operating System: null
- Node version: 20.8.0
- npm version: 10.2.0

## Description

Added Github workflow to build a Docker Image and automatically push it on Docker Hub
Upgraded the Github action version and in prevision make everything working for the new LTS of NodeJS 20

The Github workflow ASS CI build and test the build ASS then makes a Docker Image of it, and after this push it to Docker Hub, when all of the previous stuff is done, it can send Discord notification everything is ready or not.

This would help a lot of people on deploying ASS on Portainer instance or just with Docker Compose, automated everything and maybe if you want it, you can add cypress or eslint or both to the repository so I can make a workflow for testing code.

[Contributing Guidelines]: https://github.com/tycrek/ass/blob/master/CONTRIBUTING.md
[ISC License]: https://github.com/tycrek/ass/blob/master/LICENSE

2023-10-12 01:33 UTC, tycrek requested changes
Just the one thing to change (see review comments)

2023-10-12 01:33 UTC, tycrek commented on .github/workflows/ts-build.yml
All looks good here :)

2023-10-12 01:33 UTC, tycrek commented on .github/workflows/docker-build
> +          password: ${{ secrets.GITHUB_TOKEN }}
I'm opting to not use GHCR so remove these lines

2023-10-12 01:33 UTC, tycrek commented on .github/workflows/docker-build
Overall looks good, just one comment within

2023-10-12 01:33 UTC, tycrek commented on .github/workflows/codeql-analysis.yml
> +        language: [ 'javascript-typescript' ]
[Future reference](https://docs.github.com/en/code-security/code-scanning/creating-an-advanced-setup-for-code-scanning/customizing-your-advanced-setup-for-code-scanning) (ignore this comment)

2023-10-12 01:35 UTC, Gauvino commented
LGTM !

2023-10-12 01:43 UTC, tycrek approved these changes

2023-10-12 01:45 UTC, tycrek commented
All looks good! Just going to set up Secrets stuff prior to merge

2023-10-13 21:31 UTC, tycrek requested changes
One tiny thing

2023-10-13 21:31 UTC, tycrek commented on .github/workflows/docker-build.yml
> +    branches: [ master ]
One last thing, can you add `dev/0.15.0` branch to these arrays (**not** push? That way we can test it live (don't worry about the `tags: | \n tycrek/ass:master` below, that can stay as-is).

2023-10-13 22:00 UTC, tycrek approved these changes
![image](https://github.com/tycrek/ass/assets/29926144/4cf624e7-6bda-4579-ac1b-0e8b6422ffb2)

2023-10-13 22:01 UTC, merged